language: java
jdk:
- oraclejdk8
encoding: utf8
script:
- gradle assemble
- gradle publish
deploy:
  provider: bintray
  file: bintray.json
  user:
    secure: WeE37LnREki6AyLntYXae8Mz/oGRQtge2wiM+rc3Q3E0cy8372Gjz1eES79ljzo+W6HQZ1TFfsiRgGeOfib0EOtDP9KnBFNryS1amKophs1U4A6gRuPxv8v9tEoRx6izULppkR3OWQj1F3Qsl/Gn0N8dGjtibkRlRg3zRKnpUBtRjSZW3jPYN3Jh5iDZDV4cCYR2rNnlA+P47G0KRroDcLmt/3c7hnx65wzwMbbM1lCRR/xBNC5N7fVtmqb/7C/1+LdiPoQRCIK2Hb8RccdwvKF2k8DCN5QEsaU+XRkmW/zgylG4g1EmkpESmX9fIvAGxA80iyP9RfE4tMRY36HuzBO3Jq5bubq/9ZdHi8/l5jw4GeOjEtvHN4qmEW70YTDfyKqagO08beUnV8zw8h6qImgHP9ty13mcSX0PhcLsUXUAbFgq62zrnU2hLa07RAqeA/qRpfAcEkLpyHw9BNOZEawiMMpwiELlgUlfh6Q0+oeHk6Fa4KVd11pGpo8VF4Eyh/TCcjBNU0iZ45VvnzT+32yyhQZBAFWdp5XWX2wfSXe9CtuCYdc8F8VrjZP+Abw+BJiZ8ZRPI8PWT5edzh/M4hyKduBIZ8zt1UsqyQzgPD+sLEkzU1KHMtzMCLiTK/pXhpuGOBrytubZUwCQuc0U9FNsB+nqxOXIsU5uyuLeNKo=
  key:
    secure: Vxpafvx2YuWkhIFWJVGiIU76d/FcghJS4hU8BhGr/WBkmyLTqV+mH/ki55Hww3cwZ51HrWvxxocXU0QUvHlkUuTw+COXUEpgRQgit7dSWt/vorGv5oC7w6Ks5Nxd0UsIYOpWpwC6u4uzzTXlLJaADAJ/knpbFU4JMnQNZ31/IGwHaXPSq8bjcvZuY9/iv6SOPvfMZgaOw0BhRCSmdH6rGVugIV9aJphEVs6PI1rfJ3t4hn8LKfn8JuZdSWGx1pZHxAKUhlOZDxNdpnMx2uwLbbGDu8Bqn3Ak2wzADCoV9ebnlLVOwGdYbShdbgNVGZofXdO8kTAPIBTAeAu2E/KMjpESeuq5xb4PTaWXLHqxqVFowo0tcxgXBCX7BTgaq3qLsxths5wRQzJbVmAbXlXE1LrG9UEMtY9PHfC2e6Nuok41ndSPkJpzzkVduYtbyR5k1JLJUzG0bIp6gllgVSg3D/2iY0wFmxslidA6JkDEPgM74+OusBLxM5AKzeyHReo6aJknGNG5xw2V8EDgXfUv318priP8pXhZXPQi7+zK/LfFK3ftXOUyauVIAlf4OXkNrWBvNsHE6UK/xr5NeiMVYk22US1sPpAjRtrUSmK3yz61tYv0vIR9eC9M/YQOQV7sZ+wHrZk+fiKUsIJHL/84vPSJcrk3+HQR6Jo9saQVyHM=
  skip_cleanup: true
  on: master
